# Generated by Django 4.2 on 2024-01-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_item_item_image_alter_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.foodiesfeed.com/wp-content/uploads/2019/04/mae-mu-oranges-ice-cream-1024x683.jpg', max_length=500),
        ),
    ]
